### ISSUE TITLE
导入大量数据时，Chrome 浏览器报错 ERR_INSUFFICIENT_RESOURCES

### ISSUE THREAD

**Issue by LIlGG** [halo-sigs/plugin-migrate#11]
## 使用设备/软件
Chrome 110.0.5481.77（正式版本） (arm64)
Halo release-2.2
plugin-migrate release-1.1.0

## 问题描述
1. 从 1.6 版本中导出数据，使用 migrate 插件导入数据，数据量如下所示。

![Snipaste_2023-02-15_10-44-57](https://user-images.githubusercontent.com/31335418/218923846-e42834df-84bf-4c37-86d1-823c6c63e639.png)

2. 导入数据，浏览器同时创建大量请求，并阻塞运行，部分数据会出现 ERR_INSUFFICIENT_RESOURCES

![Snipaste_2023-02-15_10-53-21](https://user-images.githubusercontent.com/31335418/218924330-d740c615-9d2c-4400-a62d-b77e095b9f6c.png)

**无论网速快慢，该问题均会在本地及远端出现，且出现率百分百**

## 原因分析
浏览器会对同一个请求进行阻塞，可能是达到了挂起请求的配额阈值，或者是达到了内存上限。因为网速快慢均会出现此问题，所以排除超时的原因。

## 预设解决方案
1. 前端使用缓存队列，对请求进行分批次处理，而不是一次性全部进行发送导致阻塞在浏览器端。为了达到最大程度的并发上限，可以对不同的请求同批次发送。
2. 后端接收请求时，可以接收数组，前端对数组按照 post 请求参数最大值进行分割，可以减少大量的请求。

/kind bug

**Comment by ruibaby** [comment]
可以考虑先在前端使用队列的方式进行请求，可以参考：https://github.com/halo-dev/console/blob/381c3e24841e70b377c5670d5f0fd1f462e0d4f5/src/components/editor/DefaultEditor.vue#L344-L367
