### ISSUE TITLE
Request to release a new version

### ISSUE THREAD

**Issue by JohnNiang** [halo-sigs/plugin-migrate#15]
Recently, I found a new improvement from <https://github.com/halo-sigs/plugin-migrate/pull/12>. It is useful for me to migrate too many posts from 1.6.x.

**Comment by ruibaby** [comment]
等 2.3.0 发布还有一点修改。

**Comment by ruibaby** [comment]
https://github.com/halo-sigs/plugin-migrate/releases/tag/v1.2.0

/close
