### ISSUE TITLE
增加 1.x 日志及图库的数据迁移

### ISSUE THREAD

**Issue by LIlGG** [halo-sigs/plugin-migrate#16]
希望增加 Halo 1.x 日志与图库的迁移功能。

由于 2.x 版本日志与图库是基于插件开发的，而不同的插件对于日志与图库的模型可能不同，因此日志与图库的迁移模型需要进行讨论。目前计划分别与 https://github.com/halo-sigs/plugin-moments 及 https://github.com/halo-sigs/plugin-photos 保持一致

**Comment by ruibaby** [comment]
> 而不同的插件对于日志与图库的模型可能不同，因此日志与图库的迁移模型需要进行讨论

只考虑支持 [halo-sigs/plugin-moments](https://github.com/halo-sigs/plugin-moments) 和 [halo-sigs/plugin-photos](https://github.com/halo-sigs/plugin-photos)。
