### ISSUE TITLE
重构此插件的导入策略，支持多个 Provider

### ISSUE THREAD

**Issue by ruibaby** [halo-sigs/plugin-migrate#2]
期望重构此插件的导入逻辑，来源不仅局限于 Halo 1.x，能够做到选择不同的导入来源/导入方式。

/kind feature
/priority important-longterm

**Comment by xyhcode** [comment]
会支持hexo的导入嘛 在其他平台文章挺多的

**Comment by ruibaby** [comment]
预计在 2.1.0 发布之后开始着手这个功能。

**Comment by xiuyuanjun** [comment]
现在是不是已经开始开发了，2.1.0已经发布了？
