### ISSUE TITLE
无法选择从Halo中导出的JSON数据文件

### ISSUE THREAD

**Issue by YuanNing-96** [halo-sigs/plugin-migrate#3]
部署halo的方式：docker 
镜像：halohub/halo：2.0.0
插件版本：1.0.1
反向代理：nginx(我试了直接进入8090端口，还是同样的问题)
问题：
点击迁移-》选择文件后，会直接弹出所选文件不符合要求，但是此时还没有选择文件

**Comment by JohnNiang** [comment]
因为 Firefox 没有提供选择文件的 API，所以暂时无法支持 Firefox 浏览器迁移。

> https://docs.halo.run/getting-started/migrate-from-1.x

![image](https://user-images.githubusercontent.com/16865714/205001842-f9fd7508-d483-4719-8eea-4dda45c8f463.png)

**Comment by ruibaby** [comment]
@YuanNing-96 @JohnNiang 不仅仅是因为仅 Chrome 支持，因为目前是直接在前端通过浏览器 API 读取文件，这个 API 必须要求站点是 https 协议。 参考：https://github.com/halo-dev/halo/issues/2810#issuecomment-1333157446

**Comment by YuanNing-96** [comment]
明白了，感谢解答
同时发现了Windows自带的Edge浏览器也可以使用迁移功能，
所以如果还没装chrome的话，可以少装一个浏览器
