### ISSUE TITLE
[bug] 1.5.x版本迁移数据后,列表筛选无法找到对应之前的草稿文章等数据

### ISSUE THREAD

**Issue by stars-one** [halo-sigs/plugin-migrate#31]
1.5.x迁移2.10.0版本,之前博客有些草稿和私密类型的文章,迁移过来后数据都可以看得见

但是如果是在2.10.0版本后台管理的文章列表**点击筛选未发布状态**,文章列表却是显示的空的

如下图所示

![image](https://github.com/halo-sigs/plugin-migrate/assets/31400169/541f225d-b0f3-48a7-b872-0a317ed4fd52)

下面这个是我其中一篇属于未发布的文章,通过文章关键字查找列表可以显示出来

![image](https://github.com/halo-sigs/plugin-migrate/assets/31400169/9061344a-9d5a-48dc-9d4f-706062cae3f1)

**Comment by LIlGG** [comment]
这是 halo 状态筛选时的 bug，我已经在 halo 中提了一个新的 issue。

后续可跟踪此 issue https://github.com/halo-dev/halo/issues/4730

/close
