### ISSUE TITLE
【BUG】关于description标签和content:encoded标签的识别问题

### ISSUE THREAD

**Issue by z-hanzhe** [halo-sigs/plugin-migrate#32]
我理解的 rss.xml 文件中应该是`description`标签内为文章描述，`content:encoded`才是文章的具体内容，但是现在的迁移仅支持识别`description`，我需要手动将`content:encoded`修改为`description`才可以进行全文迁移，而且还报错

我使用的是[Typecho RSS](https://typecho.hanzhe.site/feed)，可自行通过链接测试，在线链接不能识别很奇怪，必须将 RSS 下载为 xml 文件才行

![image](https://github.com/halo-sigs/plugin-migrate/assets/58802604/a34e0016-831b-4738-88ce-912bc7bb565f)

**Comment by LIlGG** [comment]
[RSS 标准规范](https://www.rssboard.org/rss-specification) 中实际上并没有 `content:encoded` 字段。
但本插件在适配 RSS 的时候是有做 `content:encoded` 字段处理的，如下所示：

https://github.com/halo-sigs/plugin-migrate/blob/4333476fb6cffbb128009e805a0557d6fed4e7c5/console/src/modules/rss/use-rss-data-parser.ts#L129-L132

因此应该会优先使用 `content:encoded` 作为内容，其次才会使用 `description`

**Comment by z-hanzhe** [comment]
然而他并没有优先使用，而是直接报错了....

**Comment by mygithubzz1** [comment]
确实导入typecho 的RSS订阅所有请求都会400，但是会显示导入成功不知道什么原因

**Comment by LIlGG** [comment]
> 确实导入typecho 的RSS订阅所有请求都会400，但是会显示导入成功不知道什么原因

感谢反馈。

可否提供一下 Halo 日志？我需要日志来分析 400 错误的原因。另外如果是重复导入，请求就会变为 400，因为无法重复导入同一个数据，所以也需要查看一下文章列表是否已经存在待导入的内容。

**Comment by mygithubzz1** [comment]
> > 确实导入typecho 的RSS订阅所有请求都会400，但是会显示导入成功不知道什么原因
> 
> 感谢反馈。
> 
> 可否提供一下 Halo 日志？我需要日志来分析 400 错误的原因。另外如果是重复导入，请求就会变为 400，因为无法重复导入同一个数据，所以也需要查看一下文章列表是否已经存在待导入的内容。

![image](https://github.com/halo-sigs/plugin-migrate/assets/43873715/439e38e4-b416-4278-8a4f-8a53963ef012)
[halo.log](https://github.com/halo-sigs/plugin-migrate/files/13853561/halo.log)

**Comment by mygithubzz1** [comment]
> > > 确实导入typecho 的RSS订阅所有请求都会400，但是会显示导入成功不知道什么原因
> > 
> > 
> > 感谢反馈。
> > 可否提供一下 Halo 日志？我需要日志来分析 400 错误的原因。另外如果是重复导入，请求就会变为 400，因为无法重复导入同一个数据，所以也需要查看一下文章列表是否已经存在待导入的内容。
> 
> ![image](https://private-user-images.githubusercontent.com/43873715/294760329-439e38e4-b416-4278-8a4f-8a53963ef012.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ2MzQ0MzUsIm5iZiI6MTcwNDYzNDEzNSwicGF0aCI6Ii80Mzg3MzcxNS8yOTQ3NjAzMjktNDM5ZTM4ZTQtYjQxNi00Mjc4LThhNGYtOGE1Mzk2M2VmMDEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA3VDEzMjg1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJlMGFhOWYwMDgyYTBjN2VhZGNiMzIxZjY1YjljZWRmNWRjMzFmNjJlODdkMTdmYjA2Mjc3ZmZhN2UyMmY1YmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Y05hTx5goYDB7VJPdunL5DJZ-thWAkrANsAbuZNSu4I) [halo.log](https://github.com/halo-sigs/plugin-migrate/files/13853561/halo.log)

导入的数据也是typecho中的RSS订阅文件

**Comment by LIlGG** [comment]
> 导入的数据也是typecho中的RSS订阅文件

日志中没有能够看到有明显错误的地方。方便发一份脱敏后的 RSS 地址或者文件给我吗？我用它来导入测试一下。
可以发送至我的邮箱 takagi@halo.run

**Comment by LIlGG** [comment]
> 确实导入typecho 的RSS订阅所有请求都会400，但是会显示导入成功不知道什么原因

经过测试确实存在这样的问题，原因是 RSS 内容 `content:encoded` 中具有额外的属性字段，导致解析后的 content 变成了对象，进而出现 400 错误。

/kind bug
