### ISSUE TITLE
支持上传备份文件到后端读取

### ISSUE THREAD

**Issue by ruibaby** [halo-sigs/plugin-migrate#4]
目前此插件选择 1.x 备份文件的方式是使用 Chrome 内核提供的 [File System Access API](https://developer.mozilla.org/en-US/docs/Web/API/File_System_Access_API)，这种方式虽然可以完全在前端读取到电脑上的文件内容，但是目前有以下限制。

1. 目前并不是所有浏览器都支持，请参考：https://developer.mozilla.org/en-US/docs/Web/API/File_System_Access_API#browser_compatibility
2. 必须在本地或者线上的 https 站点才能使用。

所以期望此插件可以专门为读取文件提供一个接口。

/kind feature

**Comment by cyfirst007** [comment]
Tried https. And it works. Thanks a lot.

**Comment by guqing** [comment]
> @guqing After a lot of trying, I just can't get this issue completed. Mainly because I am not familiar with plugin development. Please help us complete the issue.
> 
> 
> 
> /unassign

OK I will do it later

**Comment by xiuyuanjun** [comment]
这个问题什么时候可以解决呢？有计划没？

**Comment by JohnNiang** [comment]
> https://github.com/halo-sigs/plugin-migrate/issues/4#issuecomment-1364835903

尽可能在 Halo 2.1.0 发布之前搞定这个问题，以方便大家从 Halo 1.x 迁移到 Halo 2.x。
